### PR TITLE
Update image to 0.13.0

### PR DESCRIPTION
**Pull request by fakuivan**
Quassel now uses qt5 and adds features like LDAP

https://quassel-irc.org/node/134

### CODE REVIEW

**Comment by fakuivan** [comment]
Part of the output from the configure stage: 

```
-- The following features have been enabled:

 * WANT_CORE, Build the core (server) binary
 * WANT_MONO, Build the monolithic (all-in-one) binary
 * WITH_BUNDLED_ICONS, Install required icons from the Breeze icon theme
 * SSL support in Qt, Use secure network connections
 * syslog.h, Provide support for logging to the syslog
 * Qt Linguist Tools, Translation support for Quassel

-- The following OPTIONAL packages have been found:

 * PkgConfig
 * Git

-- The following RECOMMENDED packages have been found:

 * Qt5DBus, D-Bus support for Qt5, <https://www.qt.io/>
   Needed for supporting D-Bus-based notifications and tray icon, used by most modern desktop environments
 * Qt5LinguistTools, contains tools for handling translation files
   Required for having translations
 * ZLIB, a popular compression library, <http://www.zlib.net>
   Use the most common library for protocol compression, instead of the bundled miniz implementation

-- The following REQUIRED packages have been found:

 * Qt5Core (required version >= 5.2.0), contains core functionality for Qt, <https://www.qt.io/>
 * Qt5Network, the network module for Qt5
 * Qt5Gui, the GUI module for Qt5
 * Qt5Widgets, the widgets module for Qt5
 * Qt5Script, provides scripting support for Qt5
 * Qt5Sql, the database support module for Qt5

-- The following features have been disabled:

 * WANT_QTCLIENT, Build the client-only binary (requires a core to connect to)
 * WITH_KDE, Integrate with the KDE Frameworks runtime environment
 * WITH_OXYGEN_ICONS, Support the Oxygen icon theme (KDE4)
 * EMBED_DATA, Embed icons and translations in the binaries instead of installing them
 * WITH_WEBKIT, QtWebKit and QtWebKitWidgets modules, Support showing previews for URLs in chat (legacy)
 * WITH_WEBENGINE, QtWebEngine and QtWebEngineWidgets modules, Support showing previews for URLs in chat

-- The following OPTIONAL packages have not been found:

 * LibsnoreQt5 (required version >= 0.7.0), a cross-platform notification framework, <https://projects.kde.org/projects/playground/libs/snorenotify>
   Enable support for the snorenotify framework
 * Qca-qt5
 * ExecInfo, a library for inspecting backtraces
   Used for generating backtraces in case of a crash
 * Ldap

-- The following RECOMMENDED packages have not been found:

 * dbusmenu-qt5, a library implementing the DBusMenu specification, <https://launchpad.net/libdbusmenu-qt>
   Required for having a context menu for the D-Bus-based tray icon
 * Qt5Multimedia, Multimedia support for Qt5, <https://www.qt.io/>
   Required for audio notifications
 * Phonon4Qt5, a multimedia abstraction library, <https://projects.kde.org/projects/kdesupport/phonon>
   Required for audio notifications
 * Qt5WebEngine, a WebEngine implementation for Qt, <https://www.qt.io/>
   Needed for displaying previews for URLs in chat
 * ECM, extra modules for CMake, maintained by the KDE project, <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>
   Required to find KDE Frameworks components
 * QCA2-QT5, Qt Cryptographic Architecture, <https://projects.kde.org/projects/kdesupport/qca>
   Required for encryption support
```

Noted packages not installed: 
* Qca-qt5
* Ldap
* QCA2-QT5

**Comment by fakuivan** [comment]
For Qca-qt5 there's a package called ``qca-dev`` on ``alpine:edge`` that provides this library (https://pkgs.alpinelinux.org/contents?file=&path=*Qca-qt5*&name=&branch=edge&arch=x86_64), but ``qca-dev`` on ``alpine:3.8`` this package does not exist as qt5 (https://pkgs.alpinelinux.org/contents?file=&path=*Qca-qt5*&name=&branch=v3.8&arch=x86_64)

**Comment by fakuivan** [comment]
I can confirm this produces a usable core. Without any missing features except the ones listed on my previous comment.

As a side note, I doubt the utility of ``-DWANT_MONO=ON``, as we don't want to build the monolithic client, just the core

**Comment by fakuivan** [comment]
Anyone feel free to suggest or make changes, I'm not going to be able to contribute to this PR for some time.

**Comment by ShaRose** [comment]
It looks like adding openldap-dev to build and libldap to runtime works for ldap support. I say it looks as while it offers to configure it, and says it's connected to my active directory server in logs, I can't coax it to actually accept. Usually I'm getting LDAP search failed: Operations error, which I know it my fault, but I just don't care enough to mess with it since I'll never actually use ldap.

As for QCA, it doesn't seem like it's going to be possible under alpine 3.8 since the required package is still using qt4 and there isn't a dedicated qt5 package available.

Also, just confirming that -DWANT_MONO should be OFF.

**Comment by fakuivan** [comment]
https://github.com/PeterDaveHello/tor-socks-proxy/blob/66753a51618edab758f90b3a481144e4cd9cccdb/Dockerfile#L9

Maybe the apk @ syntax can be used to fetch packages from the edge repo? Just a thought.

**Comment by ShaRose** [comment]
Finally got some time able to test it out, and it looks like you can (I didn't know that tagged repositories were a thing). You need to add the main and community edge repos however, since qca pulls in libcrypto1.1 and libssl1.1 (which aren't in the 3.8 repos as they use 1.0).

**Pull request closed without merging**
