### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Motophan**
How to use posgresql

### CODE REVIEW

**Comment by Motophan** [comment]
I am closing this pr because of the noninclusive nature of linuxserver community.

**Comment by Motophan** [comment]
Sorry need to close with comment.

**Comment by Roxedus** [comment]
This had no chance to be merged, as it was filed incorrectly, which you would have known if you followed the PR template and read the https://github.com/linuxserver/docker-quassel-core/blob/master/.github/CONTRIBUTING.md file.

**Comment by Motophan** [comment]
This is exactly what I'm talking about. Banned over reporting documentable
issues. Replies to troll me after banning.

**Comment by Roxedus** [comment]
Im telling you the result of this PR would be the same readme as it currently, as our pipeline generates the readme based on the contents of the readme vars file.

Your ban is due to the negative, bordering hostile attitude you also show now.

**Comment by Motophan** [comment]
No, it's because your community is not inclusive. I brought up the
legitimate issues respectfully and was banned by one of the other
moderators. It's unfortunate that the moderators of the discord do not
allow legitimate issues to be brought forward (regarding other containers),
but accusing me of being hostile is a bit much.

Please do not reply to this issue, I do not want to continue what you
describe as negativity or borderline hostility. I want to leave on a good
note, as I am never allowed to communicate in the discord community again
yes I brought up legitimate concerns with the next cloud container. That is
unrelated to this issue, this issue is closed.

**Pull request closed without merging**
