### PR TITLE
Quassel version 0.13.0 

### PR DESCRIPTION
**Pull request by CHBMB**
Quassel has released a new stable version, only issue is it's a one way upgrade.  
https://quassel-irc.org/node/134

### CODE REVIEW

**Comment by sparklyballs** [comment]
this needs rebasing to ubuntu 

the alpine build currently cripples most of the security features like encryption between client and server. 

there is a ppa for ubuntu at....

https://launchpad.net/~mamarley/+archive/ubuntu/quassel

**Comment by CHBMB** [comment]
@sparklyballs Thanks man, I was starting to come around to that way of thinking.  Happy Christmas to my friend whose balls are truly sparkling, may they continue to do so well into 2019 :grinning:

**Comment by CHBMB** [comment]
@sparklyballs Small problem, that PPA only contains the monolithic Quassel build, which pulls in a *lot* of extra dependencies, so I guess I'm back to compiling from source.... FML

**Comment by thelamer** [comment]
@CHBMB @sparklyballs There is an example of using a PPA endpoint to get exact versions of a program in this branch of qbittorrent if your interested https://github.com/linuxserver/docker-qbittorrent/tree/pipeline

**Pull request closed without merging**
